(defun my-python-send-region (&optional beg end)
   (interactive)
   (let ((beg (cond (beg beg)
                    ((region-active-p)
                     (region-beginning))
                    (t (line-beginning-position))))
         (end (cond (end end)
                    ((region-active-p)
                     (copy-marker (region-end)))
                    (t (line-end-position)))))
     (python-shell-send-region beg end)))

(define-key elpy-mode-map (kbd "<C-return>") 'my-python-send-region)
(provide 'setup-ipython)
